apiVersion: v1
kind: PersistentVolume
metadata:
  name : pv-vol
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /f/kube-mount 
  claimRef:
    apiVersion: v1 
    kind: PersistentVolumeClaim 
    name: jupyter-xyz 
    namespace: default 
