apiVersion: v1
kind: Pod
metadata:
  name: amazonlinux
  labels:
    app: amazonlinux
spec:
  containers:
  - name: amazonlinux
    image: amazonlinux
    command: ["/bin/sleep", "3650d"]
    imagePullPolicy: IfNotPresent
  restartPolicy: Always