apiVersion: v1
kind: Pod
metadata:
  name: jupyter-notebook
  labels:
    app: jupyter-notebook
spec:
  containers:
    - name: jupyter-pod
      image: jupyter/datascience-notebook:latest
      ports:
        - containerPort: 8888
          name: http 
      command: ["/bin/bash", "-c"]
      args: ["start.sh jupyter lab --LabApp.ip='0.0.0.0' --LabApp.allow_root=True --LabApp.notebook_dir = '/home/ubuntu/kube-mount' "]
