apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: deployment-label
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: springbackend
        image: osho/backend:latest
