
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
  labels:
    app: nginx-deployment
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx-dep
  type: LoadBalancer
  externalIPs:
  - 64.225.86.219