
apiVersion: v1
kind: Service
metadata:
  name: backend-loadbalancer
  labels:
    app: backend-loadbalancer
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: backend
  type: LoadBalancer
  externalIPs:
  - 64.225.86.219