---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: db
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: manual
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name : pv-vol-db
spec:
  storageClassName: db
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /root/db
    type: Directory
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name : pv-vol
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /root/pv
    type: Directory

