
apiVersion: v1
kind: Service
metadata:
  name: backend-nodeport
  labels:
    app: backend-svc-label
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: deployment-label
  type: NodePort