apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: deployment-label
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: springbackend
        image: 131872871854.dkr.ecr.ap-south-1.amazonaws.com/springbackend:latest
        ports:
          - containerPort: 8081
        imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: backend-nodeport
  labels:
    app: backend-svc-label
spec:
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 31234
  selector:
    app: backend
  type: NodePort