
apiVersion: v1 
kind: PersistentVolume
metadata:
  name: pv-vol
  labels:
    volname: pv-vol
spec:
  storageClassName: manual
  capacity: 
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/ubuntu/kube-mount

---

apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: pv-claim
  labels:
    claimLabel: pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

--- 


apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: deployment-label
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: springbackend
        image: nginx
        ports:
          - containerPort: 80
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /data 
            name: host-vol
      
      volumes:
        - name: host-vol
          persistentVolumeClaim:
            claimName: pv-claim

---

apiVersion: v1
kind: Service
metadata:
  name: backend-nodeport
  labels:
    app: backend-svc-label
spec:
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31234
  selector:
    app: backend
  type: NodePort
